### ISSUE TITLE
Only lasts about 20 seconds

### ISSUE THREAD

**Issue by Snookieboy** [parrotgeek1/switchdns#1]
Browsing seems to last only about 20 seconds before the Switch knows the internet works and closes the Browser.

Looking at the DNS traffic, the key point seems to be when it can get the correct IP for:

Respuesta: conntest.nintendowifi.net. -> 69.25.139.140
Respuesta: conntest.nintendowifi.net. -> 69.25.139.140

Blocking that at the router seems to allow more time with the Web Browser.

This is tested on a European Switch (UK), on 2.0.0

**Comment by parrotgeek1** [comment]
Going to block that IP unless you click cancel on URL popup

**Comment by parrotgeek1** [comment]
I fixed the bug. 
It still doesn't respond correctly with NXDOMAIN though. it just gives 0.0.0.0 because I don't know enough about dns to set the rcode in the packet
