### ISSUE TITLE
pyminifakeDNS & Windows 10

### ISSUE THREAD

**Issue by Katkat95** [parrotgeek1/switchdns#2]
> pyminifakeDNS:: dom.query. 60 IN A dynamicip
> Le chemin d’accès spécifié est introuvable.

(The specified path was not found.)
OS : Windows 10

During the launch of switchdns.py, I meet this error which prevents me from continuing you would have a solution.

Thank you for your work.

**Comment by parrotgeek1** [comment]
It only works on Windows 10's Linux emulator. Not on normal Windows.
